export default [
  require('./account/index').AccountComponent,
  require('./add-delivery-address/index').AddDeliveryAddressComponent,
	require('./add-on-details/index').AddOnDetailsComponent,
	require('./bundle/index').BundleComponent,
  require('./bundle-allergies/index').BundleAllergiesComponent,
	require('./bundle-meals/index').BundleMealsComponent,
  require('./bundle-summary/index').BundleSummaryComponent,
	require('./bundle-premium/index').BundlePremiumComponent,
  require('./calendar/index').CalendarComponent,
  require('./meal-details/index').MealDetailsComponent,
  require('./order/index').OrderComponent,
  require('./popup--allergy/index').AllergyPopupComponent,
  require('./step-progress/index').StepProgressComponent,
  require('./use-promo-code/index').UsePromoCodeComponent,
];